### ISSUE TITLE
How do you install Kafka on HDInsight Spark Clusters?

### ISSUE THREAD

**Issue by ndouba** [hdinsight/hdinsight-kafka-tools#1]
I see the kafka directory in the HDP folder but there is no service definition in AMBARI. What am I missing here?

**Comment by ravitandonrt** [comment]
@ndouba On Storm cluster Kafka is deployed using Ambari blueprints. Ideally, Ambari allows one to add Kafka or any other service through Web UI to whichever nodes they like.

Kafka is explicitly removed from Ambari stack in all other HDInsight cluster types and is only available publicly via Storm cluster today.

You can create a HDInsight Storm cluster in the same virtual network as Spark cluster and access the brokers with local names/ip addresses.

I will pass the feedback to the Spark feature team to allow the capability to install Kafka after the cluster creation and not delete it explicitly.

**Comment by ravitandonrt** [comment]
Apache Kafka on Azure HDInsight is now in public preview. Please check this blog for more information: https://azure.microsoft.com/en-us/blog/kafka-for-azure-hdinsight-now-public-preview/

Getting started: https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-apache-kafka-get-started
