### ISSUE TITLE
Add ability to limit bandwidth usage during data migration

### ISSUE THREAD

**Issue by joelhulen** [hdinsight/hdinsight-kafka-tools#5]
I'm referencing the `-throttle` parameter of `kafka-reassign-partitions.sh` as documented [here](https://kafka.apache.org/documentation.html#rep-throttle).

There should be a way to pass in a throttle parameter so that it's possible to limit the impact these data-intensive operations will have on users.

The other key step will be to remove the throttle after rebalancing. Simply ensuring verification once the rebalancing has completed should remove the throttle automatically.

**Comment by anoopsjohn** [comment]
Seems an old issue.   The throttle limit addition support is added into the python script for rebalance

_parser.add_argument('--throttle', help='Upper bound on bandwidth used to move replicas from machine to machine.')_
